import { useState, useEffect } from 'react'
import { geminiService } from '../services/geminiService'

export function AIRecommendations({ book }) {
  const [recommendations, setRecommendations] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        setLoading(true)
        setError(null)
        const recs = await geminiService.getBookRecommendations(book.title, book.author)
        setRecommendations(recs)
      } catch (err) {
        setError('Failed to load recommendations')
        console.error('Error fetching recommendations:', err)
      } finally {
        setLoading(false)
      }
    }

    if (book) {
      fetchRecommendations()
    }
  }, [book])

  if (loading) {
    return (
      <div className="card p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">AI-Powered Recommendations</h2>
        <div className="space-y-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="animate-pulse">
              <div className="bg-gray-200 h-6 rounded mb-2 loading-pulse"></div>
              <div className="bg-gray-200 h-4 rounded w-3/4 loading-pulse"></div>
            </div>
          ))}
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="card p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">AI-Powered Recommendations</h2>
        <div className="text-center py-8">
          <div className="text-4xl mb-4">🤖</div>
          <p className="text-gray-600">Unable to load recommendations at this time.</p>
        </div>
      </div>
    )
  }

  return (
    <div className="card p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-2">AI-Powered Recommendations</h2>
      <p className="text-gray-600 mb-6">Books similar to "{book.title}" recommended by AI</p>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {recommendations.map((rec, index) => (
          <div key={index} className="bg-gray-50 rounded-lg p-6 hover:bg-gray-100 transition-colors">
            <div className="flex items-center justify-center w-12 h-12 bg-primary-100 rounded-lg mb-4">
              <span className="text-primary-600 font-bold text-lg">📖</span>
            </div>
            <h3 className="font-semibold text-gray-900 mb-2 line-clamp-2">
              {rec.title}
            </h3>
            <p className="text-gray-600 text-sm">
              by {rec.author}
            </p>
          </div>
        ))}
      </div>
      
      <div className="mt-6 p-4 bg-blue-50 rounded-lg">
        <p className="text-sm text-blue-700">
          <span className="font-medium">💡 Pro tip:</span> These recommendations are generated by AI based on the book's content, genre, and style. Consider adding them to your reading list!
        </p>
      </div>
    </div>
  )
}